/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zhaozx_JniTest */

#ifndef _Included_zhaozx_JniTest
#define _Included_zhaozx_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zhaozx_JniTest
 * Method:    getPackname
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zhaozx_JniTest_getPackname
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
